export default {
	CREATE_COURSE: 'CREATE_COURSE',
	UPDATE_COURSE: 'UPDATE_COURSE',
	LOAD_COURSES: 'LOAD_COURSES',
	DELETE_COURSE: 'DELETE_COURSE',
	CREATE_AUTHOR: 'CREATE_AUTHOR',
	UPDATE_AUTHOR: 'UPDATE_AUTHOR',
	LOAD_AUTHORS: 'LOAD_AUTHORS',
	DELETE_AUTHOR: 'DELETE_AUTHOR',
};
